name = "Certificates"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Certificates"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "CertifyingInvariantsNF"
scope = "alainchmt"
main = "main"
git = "https://github.com/alainchmt/CertifyingInvariantsNF"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0-rc1"

[[lean_lib]]
name = "Certificates"
